### ISSUE TITLE
Add logging info

### ISSUE THREAD

**Issue by pnallin** [lnls-sirius/eth-bridge-pru-serial485#33]
- Logging into /var/log/
- Log messages with no reply (empty reply) from power supplies

**Comment by gfrn** [comment]
Added on #36 (alongside unit tests)

**Comment by xresende** [comment]
@pnallin , I just would like to remind that eth-bridge logging for SI correctors may impact SOFB performance. we should evaluate the performance before deploying it. SOFB has now stats PVs that make this evaluation easy.

**Comment by gfrn** [comment]
> @pnallin , @gfrn , I just would like to remind that eth-bridge logging for SI correctors may impact SOFB performance. we should evaluate the performance before deploying it. SOFB has now stats PVs that make this evaluation easy.

@xresende Since the addition of error-checking routines has an impact on performance, I've ran a few tests with `timeit`, running 5 iterations of 10000 requests each for various conditions:

Old client, old server
`[18.436726126994472, 18.953099301012116, 18.831665039993823, 19.028587622000487, 19.17461112899764]`
- Average: 18.884937843799708 seconds per 10000 requests
- Std. Dev.: 0.2796978681947056 seconds

New client, new server (unoptimized, pre-last commit)
`[18.967432147008367, 18.77542293300212, 19.210577290999936, 18.989860518006026, 19.231212487997254]`
- Average: 19.03490107540274 seconds per 10000 requests (+0.1499632316030315 over old version)
- Std. Dev.: 0.1892814821465473 seconds

New client, new server (optimized)
`[19.12700529299036, 18.778207933006343, 17.843663115010713, 18.329608821994043, 18.883355704005226]`
- Average: 18.592368173401336 seconds per 10000 requests (-0.2925696703983718 over old version)
- Std. Dev.: 0.5085884264489149 seconds

Tests were ran at 3 MBd, on the same hardware for both the client and server. For now, only errors, startups and unconventional situations are being logged.

Client:
- CPU: Intel Xeon E3-1270 v5 (8) @ 4.000GHz  
- Memory: 32032MiB
- OS: Xubuntu 21.10 x86_64 

There are a few more situations where I believe we could extract more performance, but that would fall under a "diminishing returns" kind of situation. Either way, I've created an issue with a few alterations and performance improvement suggestions that require more attention.
